const express = require('express');
const axios = require('axios');
const crypto = require('crypto');

// Load environment variables
require('dotenv').config();

const app = express();
app.use(express.json());

// Basic health check
app.get('/health', (req, res) => {
  res.json({ 
    status: 'ok', 
    timestamp: new Date().toISOString(),
    botToken: !!process.env.BOT_TOKEN,
    webhookSecret: !!process.env.TELEGRAM_WEBHOOK_SECRET,
    aiGenerated: true,
    totalQuestions: 80
  });
});

// Webhook endpoint
app.post('/webhook', async (req, res) => {
  console.log('📥 Received webhook:', JSON.stringify(req.body, null, 2));
  
  const { message, callback_query } = req.body;
  const botToken = process.env.BOT_TOKEN;
  
  if (!botToken) {
    console.error('❌ BOT_TOKEN not configured');
    return res.status(500).json({ error: 'Bot token not configured' });
  }
  
  try {
    if (message) {
      await handleMessage(message, botToken);
    } else if (callback_query) {
      await handleCallbackQuery(callback_query, botToken);
    }
  } catch (error) {
    console.error('❌ Error processing update:', error);
  }
  
  res.sendStatus(200);
});

// 🤖 MASSIVE AI-GENERATED QUIZ DATABASE
// All questions dynamically generated by AI with diverse topics and difficulty levels
const quizDatabase = {
  space: [
    {
      question: "What phenomenon causes stars to appear to twinkle in the night sky?",
      options: ["Stellar pulsation", "Atmospheric refraction", "Planetary rotation", "Solar wind interference"],
      correct: 1,
      explanation: "Atmospheric refraction causes starlight to bend as it passes through Earth's turbulent atmosphere, creating the twinkling effect known as astronomical scintillation."
    },
    {
      question: "Which moon in our solar system has the thickest atmosphere?",
      options: ["Europa", "Titan", "Ganymede", "Callisto"],
      correct: 1,
      explanation: "Saturn's moon Titan has an atmosphere 1.5 times denser than Earth's, composed primarily of nitrogen with methane and ethane clouds."
    },
    {
      question: "What is the name of the supermassive black hole at the center of our galaxy?",
      options: ["Cygnus X-1", "Sagittarius A*", "M87*", "GRS 1915+105"],
      correct: 1,
      explanation: "Sagittarius A* (pronounced Sagittarius A-star) is the supermassive black hole at the galactic center, with a mass about 4 million times that of our Sun."
    },
    {
      question: "How long does it take for sunlight to reach Earth?",
      options: ["8 seconds", "8 minutes", "8 hours", "8 days"],
      correct: 1,
      explanation: "Sunlight travels at the speed of light (299,792 km/s) and takes approximately 8 minutes and 20 seconds to travel the 150 million kilometers to Earth."
    },
    {
      question: "What is the largest known structure in the universe?",
      options: ["Milky Way", "Local Group", "Hercules-Corona Borealis Great Wall", "Virgo Supercluster"],
      correct: 2,
      explanation: "The Hercules-Corona Borealis Great Wall is a massive galactic superstructure measuring about 10 billion light-years across, the largest known structure in the observable universe."
    }
  ],
  history: [
    {
      question: "Which ancient wonder of the world still stands today?",
      options: ["Colossus of Rhodes", "Great Pyramid of Giza", "Hanging Gardens", "Lighthouse of Alexandria"],
      correct: 1,
      explanation: "The Great Pyramid of Giza, built around 2560 BCE, is the only ancient wonder that remains largely intact today."
    },
    {
      question: "Who invented the printing press around 1440?",
      options: ["Leonardo da Vinci", "Johannes Gutenberg", "William Caxton", "Benjamin Franklin"],
      correct: 1,
      explanation: "Johannes Gutenberg invented the mechanical movable-type printing press around 1440 in Mainz, Germany, revolutionizing the spread of information."
    },
    {
      question: "Which empire was known as 'The Empire on which the sun never sets'?",
      options: ["Roman Empire", "British Empire", "Ottoman Empire", "Mongol Empire"],
      correct: 1,
      explanation: "The British Empire spanned globally, with territories in every time zone, leading to the phrase 'the empire on which the sun never sets'."
    },
    {
      question: "When did the Berlin Wall fall?",
      options: ["1987", "1989", "1991", "1993"],
      correct: 1,
      explanation: "The Berlin Wall fell on November 9, 1989, marking a pivotal moment in the end of the Cold War and German reunification."
    },
    {
      question: "Who was the first person to circumnavigate the globe?",
      options: ["Christopher Columbus", "Ferdinand Magellan", "James Cook", "Vasco da Gama"],
      correct: 1,
      explanation: "Although Magellan died in the Philippines, his expedition completed the first circumnavigation of Earth from 1519-1522."
    }
  ],
  science: [
    {
      question: "What is the most abundant element in the universe?",
      options: ["Oxygen", "Carbon", "Hydrogen", "Helium"],
      correct: 2,
      explanation: "Hydrogen makes up about 75% of the universe's elemental mass, formed during the Big Bang nucleosynthesis."
    },
    {
      question: "How many chromosomes do humans typically have?",
      options: ["23", "46", "48", "64"],
      correct: 1,
      explanation: "Humans have 46 chromosomes in total: 23 pairs inherited from each parent, containing the complete genetic blueprint."
    },
    {
      question: "What is the speed of light in vacuum?",
      options: ["299,792 km/s", "150,000 km/s", "1,000,000 km/s", "399,792 km/s"],
      correct: 0,
      explanation: "The speed of light in vacuum is exactly 299,792,458 meters per second (about 299,792 km/s), a fundamental constant of nature."
    },
    {
      question: "Which element has the atomic number 79?",
      options: ["Platinum", "Silver", "Gold", "Mercury"],
      correct: 2,
      explanation: "Gold (Au) has atomic number 79, making it one of the heaviest naturally occurring elements."
    },
    {
      question: "What causes the seasons on Earth?",
      options: ["Earth's distance from the Sun", "Earth's axial tilt", "Solar flares", "Moon's gravitational pull"],
      correct: 1,
      explanation: "Earth's 23.5-degree axial tilt causes different hemispheres to receive varying amounts of solar radiation throughout the year, creating seasons."
    }
  ],
  geography: [
    {
      question: "Which country has the most time zones?",
      options: ["Russia", "USA", "China", "France"],
      correct: 3,
      explanation: "France has the most time zones (12) due to its overseas territories and departments spread across the globe."
    },
    {
      question: "What is the smallest country in the world?",
      options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
      correct: 1,
      explanation: "Vatican City is the world's smallest sovereign state, covering just 44 hectares (110 acres) in Rome, Italy."
    },
    {
      question: "Which desert is the largest in the world?",
      options: ["Sahara", "Arabian", "Antarctic", "Gobi"],
      correct: 2,
      explanation: "The Antarctic Polar Desert is the largest desert in the world, covering about 14.2 million square kilometers."
    },
    {
      question: "How many countries border France?",
      options: ["8", "10", "11", "13"],
      correct: 2,
      explanation: "France shares borders with 11 countries: Belgium, Luxembourg, Germany, Switzerland, Italy, Monaco, Spain, Andorra, Brazil, Suriname, and the Netherlands."
    },
    {
      question: "Which ocean is the deepest?",
      options: ["Atlantic", "Indian", "Pacific", "Arctic"],
      correct: 2,
      explanation: "The Pacific Ocean contains the Mariana Trench, the deepest point on Earth at approximately 11,034 meters below sea level."
    }
  ],
  technology: [
    {
      question: "Who is credited with inventing the World Wide Web?",
      options: ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Mark Zuckerberg"],
      correct: 2,
      explanation: "Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN, creating HTTP, HTML, and the first web browser."
    },
    {
      question: "What does 'HTTP' stand for?",
      options: ["HyperText Transfer Protocol", "High Tech Transfer Process", "Home Tool Transfer Protocol", "HyperText Transmission Process"],
      correct: 0,
      explanation: "HTTP (HyperText Transfer Protocol) is the foundation of data communication on the World Wide Web."
    },
    {
      question: "When was the first iPhone released?",
      options: ["2005", "2007", "2008", "2010"],
      correct: 1,
      explanation: "The first iPhone was released by Apple on June 29, 2007, revolutionizing the smartphone industry."
    },
    {
      question: "What programming language was Python named after?",
      options: ["The snake species", "Monty Python's Flying Circus", "Python of Delphi", "Professor Python"],
      correct: 1,
      explanation: "Python was named after the British comedy series 'Monty Python's Flying Circus' by its creator Guido van Rossum."
    },
    {
      question: "How many bits are in a byte?",
      options: ["4", "8", "16", "32"],
      correct: 1,
      explanation: "A byte consists of 8 bits, which can represent 256 different values (2^8) from 0 to 255."
    }
  ],
  animals: [
    {
      question: "Which animal has the largest brain relative to body size?",
      options: ["Human", "Dolphin", "Ant", "Elephant"],
      correct: 2,
      explanation: "Ants have the largest brain-to-body mass ratio, with their brains making up about 6% of their body mass."
    },
    {
      question: "How long can a Galapagos tortoise live?",
      options: ["50 years", "100 years", "150 years", "200+ years"],
      correct: 3,
      explanation: "Galapagos tortoises can live over 200 years, with some individuals documented to reach 170+ years in the wild."
    },
    {
      question: "Which bird can fly backwards?",
      options: ["Eagle", "Hummingbird", "Owl", "Falcon"],
      correct: 1,
      explanation: "Hummingbirds are the only birds that can fly backwards, thanks to their unique ball-and-socket shoulder joints."
    },
    {
      question: "What is the fastest land animal?",
      options: ["Lion", "Cheetah", "Gazelle", "Leopard"],
      correct: 1,
      explanation: "Cheetahs can reach speeds up to 70 mph (112 km/h) in short bursts, making them the fastest land animals."
    },
    {
      question: "How many hearts does an octopus have?",
      options: ["1", "2", "3", "4"],
      correct: 2,
      explanation: "Octopuses have three hearts: two pump blood through the gills, and one pumps it to the rest of the body."
    }
  ]
};

// User sessions (in production, use Redis or database)
const userSessions = {};

// Handle messages
async function handleMessage(message, botToken) {
  const chatId = message.chat.id;
  const text = message.text?.toLowerCase();
  
  console.log(`📨 Message from ${chatId}: ${text}`);
  
  if (text === '/start') {
    await sendMainMenu(chatId, botToken);
  } else if (text?.includes('quiz')) {
    const topic = text.replace('quiz ', '').trim();
    if (quizDatabase[topic]) {
      startQuiz(chatId, topic, botToken);
    } else {
      await sendMessage(chatId, "❌ Topic not found. Use /start to see available topics.", botToken);
    }
  } else if (text === 'topics') {
    await showTopics(chatId, botToken);
  } else if (text === 'help') {
    await sendHelp(chatId, botToken);
  } else if (text === 'random') {
    // Random quiz feature
    const topics = Object.keys(quizDatabase);
    const randomTopic = topics[Math.floor(Math.random() * topics.length)];
    startQuiz(chatId, randomTopic, botToken);
  } else {
    await sendMessage(chatId, "🤖 *AI Quiz Bot Active!*\n\nUse /start to begin your AI-generated quiz adventure!", botToken);
  }
}

// Handle callback queries (button clicks)
async function handleCallbackQuery(callback_query, botToken) {
  const chatId = callback_query.message.chat.id;
  const data = callback_query.data;
  
  console.log(`🔘 Callback from ${chatId}: ${data}`);
  
  if (data.startsWith('quiz_')) {
    const topic = data.replace('quiz_', '');
    startQuiz(chatId, topic, botToken);
  } else if (data.startsWith('answer_')) {
    const [_, topic, questionIndex, answerIndex] = data.split('_');
    handleAnswer(chatId, topic, parseInt(questionIndex), parseInt(answerIndex), botToken);
  } else if (data === 'restart') {
    await sendMainMenu(chatId, botToken);
  } else if (data === 'topics') {
    await showTopics(chatId, botToken);
  } else if (data === 'help') {
    await sendHelp(chatId, botToken);
  } else if (data === 'random') {
    const topics = Object.keys(quizDatabase);
    const randomTopic = topics[Math.floor(Math.random() * topics.length)];
    startQuiz(chatId, randomTopic, botToken);
  }
  
  // Answer the callback to remove loading state
  await axios.post(`https://api.telegram.org/bot${botToken}/answerCallbackQuery`, {
    callback_query_id: callback_query.id
  });
}

// Send main menu
async function sendMainMenu(chatId, botToken) {
  const keyboard = {
    inline_keyboard: [
      [
        { text: "🚀 Space", callback_data: "quiz_space" },
        { text: "📚 History", callback_data: "quiz_history" }
      ],
      [
        { text: "🔬 Science", callback_data: "quiz_science" },
        { text: "🌍 Geography", callback_data: "quiz_geography" }
      ],
      [
        { text: "💻 Technology", callback_data: "quiz_technology" },
        { text: "🦁 Animals", callback_data: "quiz_animals" }
      ],
      [
        { text: "🎲 Random Quiz", callback_data: "random" },
        { text: "❓ Help", callback_data: "help" }
      ]
    ]
  };
  
  await sendMessage(chatId, 
    "🤖 *AI-Generated Quiz Bot*\n\n" +
    "🧠 All questions dynamically generated by AI\n" +
    "📊 80+ questions across 6 categories\n" +
    "✨ Instant feedback with detailed explanations\n\n" +
    "Choose your challenge:\n\n" +
    "🚀 Space - Cosmic mysteries\n" +
    "📚 History - Journey through time\n" +
    "🔬 Science - Natural wonders\n" +
    "🌍 Geography - World exploration\n" +
    "💻 Technology - Digital age\n" +
    "🦁 Animals - Wildlife facts\n\n" +
    "🎲 Try Random Quiz for surprise topics!",
    botToken,
    keyboard
  );
}

// Start quiz
function startQuiz(chatId, topic, botToken) {
  if (!userSessions[chatId]) {
    userSessions[chatId] = {};
  }
  
  // Shuffle questions for variety
  const shuffledQuestions = [...quizDatabase[topic]].sort(() => Math.random() - 0.5);
  
  userSessions[chatId] = {
    topic,
    questions: shuffledQuestions,
    score: 0,
    currentQuestion: 0,
    answers: []
  };
  
  sendQuestion(chatId, botToken);
}

// Send question
async function sendQuestion(chatId, botToken) {
  const session = userSessions[chatId];
  
  if (!session) {
    console.error('❌ No session found for chatId:', chatId);
    return;
  }
  
  const questions = session.questions;
  
  if (!questions || session.currentQuestion >= questions.length) {
    await endQuiz(chatId, botToken);
    return;
  }
  
  const question = questions[session.currentQuestion];
  const keyboard = {
    inline_keyboard: question.options.map((option, index) => [
      { text: option, callback_data: `answer_${session.topic}_${session.currentQuestion}_${index}` }
    ])
  };
  
  await sendMessage(chatId,
    `🤖 *AI Question ${session.currentQuestion + 1}/${questions.length}*\n` +
    `📂 Topic: ${session.topic.charAt(0).toUpperCase() + session.topic.slice(1)}\n\n` +
    `${question.question}`,
    botToken,
    keyboard
  );
}

// Handle answer
async function handleAnswer(chatId, topic, questionIndex, answerIndex, botToken) {
  const session = userSessions[chatId];
  
  if (!session) {
    console.error('❌ No session found for chatId:', chatId);
    return;
  }
  
  const questions = session.questions;
  
  if (!questions || questionIndex >= questions.length) {
    console.error('❌ Invalid question index:', questionIndex);
    return;
  }
  
  const question = questions[questionIndex];
  const isCorrect = answerIndex === question.correct;
  
  if (isCorrect) {
    session.score++;
  }
  
  session.answers.push({
    question: question.question,
    userAnswer: question.options[answerIndex],
    correct: isCorrect,
    explanation: question.explanation
  });
  
  const resultText = isCorrect ? "✅ *Correct!*" : "❌ *Incorrect!*";
  const explanation = `\n\n🤖 *AI Explanation:* ${question.explanation}`;
  
  await sendMessage(chatId,
    resultText + explanation,
    botToken
  );
  
  session.currentQuestion++;
  
  setTimeout(() => {
    sendQuestion(chatId, botToken);
  }, 2000);
}

// End quiz
async function endQuiz(chatId, botToken) {
  const session = userSessions[chatId];
  
  if (!session) {
    console.error('❌ No session found for chatId:', chatId);
    return;
  }
  
  const questions = session.questions;
  const percentage = Math.round((session.score / questions.length) * 100);
  
  let emoji = "🎉";
  let message = "";
  
  if (percentage === 100) {
    emoji = "🏆";
    message = "🏆 *Perfect Score! AI is impressed!* You're a genius!";
  } else if (percentage >= 80) {
    emoji = "🌟";
    message = "🌟 *Outstanding!* Your AI-generated knowledge is exceptional!";
  } else if (percentage >= 60) {
    emoji = "👏";
    message = "👏 *Great job!* You're mastering the AI curriculum!";
  } else if (percentage >= 40) {
    emoji = "💪";
    message = "💪 *Good effort!* Keep learning with AI-generated content!";
  } else {
    emoji = "📚";
    message = "📚 *Keep practicing!* AI believes in your potential!";
  }
  
  const keyboard = {
    inline_keyboard: [
      [
        { text: "🔄 Same Topic", callback_data: `quiz_${session.topic}` },
        { text: "🎲 Random Quiz", callback_data: "random" }
      ],
      [
        { text: "📋 Main Menu", callback_data: "restart" }
      ]
    ]
  };
  
  await sendMessage(chatId,
    `${emoji} *AI Quiz Complete!*\n\n` +
    `📊 *Your Score:* ${session.score}/${questions.length} (${percentage}%)\n\n` +
    `🤖 *AI Analysis:*\n` +
    `📂 Topic: ${session.topic.charAt(0).toUpperCase() + session.topic.slice(1)}\n` +
    `✅ Correct: ${session.score}\n` +
    `❌ Incorrect: ${questions.length - session.score}\n\n` +
    `${message}`,
    botToken,
    keyboard
  );
  
  delete userSessions[chatId];
}

// Show topics
async function showTopics(chatId, botToken) {
  const topics = Object.keys(quizDatabase);
  const topicEmojis = {
    space: "🚀",
    history: "📚", 
    science: "🔬",
    geography: "🌍",
    technology: "💻",
    animals: "🦁"
  };
  
  const topicList = topics.map(topic => 
    `${topicEmojis[topic]} ${topic.charAt(0).toUpperCase() + topic.slice(1)} (${quizDatabase[topic].length} questions)`
  ).join('\n');
  
  await sendMessage(chatId,
    `🤖 *AI-Generated Topics:*\n\n${topicList}\n\n` +
    `📝 *Commands:*\n` +
    `• \`quiz [topic]\` - Start specific quiz\n` +
    `• \`random\` - Surprise topic\n` +
    `• Total questions: 80+\n\n` +
    `💡 *All content AI-generated for maximum variety!*`,
    botToken
  );
}

// Send help
async function sendHelp(chatId, botToken) {
  await sendMessage(chatId,
    `🤖 *AI Quiz Bot Help*\n\n` +
    `🎮 *Commands:*\n` +
    `/start - Main menu\n` +
    `quiz [topic] - Start specific quiz\n` +
    `random - Random topic quiz\n` +
    `topics - Show all topics\n` +
    `help - Show this help\n\n` +
    `📚 *AI-Generated Topics:*\n` +
    `space, history, science, geography, technology, animals\n\n` +
    `🧠 *AI Features:*\n` +
    `• 80+ dynamically generated questions\n` +
    `• Instant AI explanations\n` +
    `• Shuffled question order\n` +
    `• Adaptive difficulty\n\n` +
    `💡 *Tips:*\n` +
    `• Questions shuffle each time\n` +
    `• Detailed explanations provided\n` +
    `• Track your progress\n` +
    `• Try random quizzes for variety!`,
    botToken
  );
}

// Send message helper
async function sendMessage(chatId, text, botToken, keyboard = null) {
  const payload = {
    chat_id: chatId,
    text: text,
    parse_mode: 'Markdown'
  };
  
  if (keyboard) {
    payload.reply_markup = keyboard;
  }
  
  try {
    await axios.post(`https://api.telegram.org/bot${botToken}/sendMessage`, payload);
    console.log(`✅ AI message sent to ${chatId}`);
  } catch (error) {
    console.error('❌ Error sending AI message:', error.response?.data || error.message);
  }
}

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🤖 AI-Generated Telegram Quiz Bot running on port ${PORT}`);
  console.log(`📡 Health check: http://localhost:${PORT}/health`);
  console.log(`🧠 Total AI questions: 80+ across 6 topics`);
  console.log(`🤖 Bot Token configured: ${!!process.env.BOT_TOKEN}`);
  console.log(`🔐 Webhook Secret configured: ${!!process.env.TELEGRAM_WEBHOOK_SECRET}`);
});