import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Users, MessageSquare, Bot, User } from 'lucide-react';
import { TelegramChat } from './TelegramChat';
import { User as UserType } from '../types/telegram';

const mockUsers: UserType[] = [
  { id: 'user1', name: 'Alice', avatar: '👩', score: 15, streak: 3 },
  { id: 'user2', name: 'Bob', avatar: '👨', score: 8, streak: 1 },
  { id: 'user3', name: 'Carol', avatar: '👩‍💼', score: 22, streak: 5 },
];

export function GroupChatSimulator() {
  const [activeUser, setActiveUser] = useState<UserType>(mockUsers[0]);
  const [showPrivate, setShowPrivate] = useState(false);

  return (
    <div className="w-full max-w-6xl mx-auto space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bot className="w-6 h-6 text-blue-600" />
            AI Quiz Bot Simulator
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="group" className="w-full">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="group" className="flex items-center gap-2">
                <Users className="w-4 h-4" />
                Group Chat
              </TabsTrigger>
              <TabsTrigger value="private" className="flex items-center gap-2">
                <MessageSquare className="w-4 h-4" />
                Private Chat
              </TabsTrigger>
            </TabsList>
            
            <TabsContent value="group" className="space-y-4">
              <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium">Simulating as:</span>
                  <div className="flex gap-2">
                    {mockUsers.map((user) => (
                      <Button
                        key={user.id}
                        variant={activeUser.id === user.id ? 'default' : 'outline'}
                        size="sm"
                        onClick={() => setActiveUser(user)}
                        className="flex items-center gap-2"
                      >
                        <span>{user.avatar}</span>
                        {user.name}
                      </Button>
                    ))}
                  </div>
                </div>
                <div className="text-sm text-gray-600">
                  Each user gets personalized AI-generated questions
                </div>
              </div>
              
              <TelegramChat
                currentUser={activeUser}
                isGroup={true}
                otherUsers={mockUsers.filter(u => u.id !== activeUser.id)}
              />
            </TabsContent>
            
            <TabsContent value="private">
              <div className="p-4 bg-blue-50 rounded-lg mb-4">
                <div className="flex items-center gap-2 text-blue-900">
                  <User className="w-4 h-4" />
                  <span className="font-medium">Private Chat Mode</span>
                </div>
                <p className="text-sm text-blue-700 mt-1">
                  One-on-one conversation with the AI Quiz Bot. All questions are personalized to your learning style.
                </p>
              </div>
              
              <TelegramChat
                currentUser={activeUser}
                isGroup={false}
              />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">How It Works</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0">
              <span className="text-green-600 font-bold text-sm">1</span>
            </div>
            <div>
              <div className="font-medium">AI-Powered Questions</div>
              <div className="text-sm text-gray-600">
                Each question is generated by GPT-4, Claude, or Gemini for unique content
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center flex-shrink-0">
              <span className="text-blue-600 font-bold text-sm">2</span>
            </div>
            <div>
              <div className="font-medium">User-Specific Conversations</div>
              <div className="text-sm text-gray-600">
                In groups, swipe-to-reply to maintain your personal quiz thread
              </div>
            </div>
          </div>
          
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 bg-purple-100 rounded-full flex items-center justify-center flex-shrink-0">
              <span className="text-purple-600 font-bold text-sm">3</span>
            </div>
            <div>
              <div className="font-medium">Multi-Engine AI</div>
              <div className="text-sm text-gray-600">
                Different AI engines provide varied question styles and difficulties
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}